name: CI
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Skip build if it's a release PR
        if: contains(github.event.pull_request.labels[0].name, '🚀release')
        run: exit 0

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: "@ktech-org"

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true
          NODE_AUTH_TOKEN:  ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test:ci
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true
